--1
SELECT policy_name FROM dba_sa_policies;

EXEC SA_SYSDBA.DROP_POLICY('SEC_POLICY');
EXEC SA_SYSDBA.DROP_POLICY('THONGBAO_OLS_DBA');
EXEC SA_SYSDBA.DROP_POLICY('THONGBAO_POLICY');
EXEC SA_SYSDBA.DROP_POLICY('NOTIFICATION1_POLICY');
EXEC SA_SYSDBA.DROP_POLICY('POL_THONGBAO');
EXEC SA_SYSDBA.DROP_POLICY('NOTIFICATION_POLICY');

SELECT policy_name FROM dba_sa_policies;

--4
EXEC SA_SYSDBA.CREATE_POLICY('NOTIFICATION_POLICY', 'LABEL_COL');

--5

EXEC SA_COMPONENTS.CREATE_LEVEL('NOTIFICATION_POLICY', 3000, 'TRUONGDV', 'Truong Don Vi');
EXEC SA_COMPONENTS.CREATE_LEVEL('NOTIFICATION_POLICY', 2000, 'NHANVIEN', 'Nhan Vien');
EXEC SA_COMPONENTS.CREATE_LEVEL('NOTIFICATION_POLICY', 1000, 'SINHVIEN', 'Sinh Vien');

--6
EXEC SA_COMPONENTS.CREATE_GROUP('NOTIFICATION_POLICY', 10, 'CS1', 'Co So 1');
EXEC SA_COMPONENTS.CREATE_GROUP('NOTIFICATION_POLICY', 20, 'CS2', 'Co So 2');

--7
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('NOTIFICATION_POLICY', 10, 'TOAN', 'Toan');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('NOTIFICATION_POLICY', 20, 'LY', 'Ly');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('NOTIFICATION_POLICY', 30, 'HOA', 'Hoa');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('NOTIFICATION_POLICY', 40, 'HANHCHINH', 'Hanh Chinh');

--8
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2001, 'TRUONGDV::');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2002, 'NHANVIEN::');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2003, 'SINHVIEN::');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2004, 'SINHVIEN:HOA:CS1');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2005, 'SINHVIEN:HOA:CS2');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2006, 'SINHVIEN:HOA:CS1,CS2');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2007, 'SINHVIEN::CS1,CS2');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2008, 'TRUONGDV:HOA:CS1');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('NOTIFICATION_POLICY', 2009, 'TRUONGDV:HOA:CS1,CS2');

--9. Kiem tra:
SELECT * FROM dba_sa_levels WHERE policy_name = 'NOTIFICATION_POLICY';
SELECT * FROM dba_sa_groups WHERE policy_name = 'NOTIFICATION_POLICY';
SELECT * FROM dba_sa_compartments WHERE policy_name = 'NOTIFICATION_POLICY';
SELECT label_tag, label FROM dba_sa_labels WHERE policy_name = 'NOTIFICATION_POLICY';

--10.
EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY('NOTIFICATION_POLICY', 'USER_ADMIN', 'THONGBAO', 'READ_CONTROL,WRITE_CONTROL');

--11. Kiem tra:
SELECT policy_name, schema_name, table_name 
FROM dba_sa_table_policies 
WHERE schema_name = 'USER_ADMIN' AND table_name = 'THONGBAO';
--12. 
EXEC SA_USER_ADMIN.SET_USER_PRIVS('NOTIFICATION_POLICY', 'USER_ADMIN', 'FULL');

--13

EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U1', 'TRUONGDV::');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U2', 'TRUONGDV:HOA:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U3', 'TRUONGDV:LY:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U4', 'NHANVIEN:HOA:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U5', 'SINHVIEN:HOA:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U6', 'TRUONGDV:HANHCHINH:');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U7', 'NHANVIEN::');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U8', 'NHANVIEN:HANHCHINH:CS1');

--16

EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U1', 'TRUONGDV::');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U2', 'TRUONGDV:HOA:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U3', 'TRUONGDV:LY:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U4', 'NHANVIEN:HOA:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U5', 'SINHVIEN:HOA:CS2');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U6', 'TRUONGDV:HANHCHINH:');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U7', 'NHANVIEN::');
EXEC SA_USER_ADMIN.SET_USER_LABELS('NOTIFICATION_POLICY', 'U8', 'NHANVIEN:HANHCHINH:CS1');