CREATE OR REPLACE FUNCTION get_vaitro RETURN VARCHAR2
--AUTHID CURRENT_USER 
IS
    v_role VARCHAR2(10);
BEGIN
    -- Lấy trong NHANVIEN
    BEGIN
        SELECT VAITRO INTO v_role
        FROM user_admin.NHANVIEN
        WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
        
        RETURN v_role;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL; -- Không tìm thấy trong NHANVIEN, thử tiếp ở SINHVIEN
    END;
    BEGIN
        SELECT 'SV' INTO v_role
        FROM user_admin.SINHVIEN
        WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER');

        RETURN v_role;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Không có trong cả NHANVIEN và SINHVIEN thì báo lỗi
            RAISE_APPLICATION_ERROR(-20001, 'Người dùng không phải nhân viên hoặc sinh viên.');
    END;
END;
/

GRANT EXECUTE ON get_vaitro TO PUBLIC;

-- LẤY THÔNG TIN GIÁO VIÊN THEO MANV

CREATE OR REPLACE PROCEDURE GET_GV_INFO (
    p_MANV IN VARCHAR2,
    p_VAITRO OUT VARCHAR2,
    p_MADV OUT VARCHAR2,
    p_TENDV OUT VARCHAR2
) AS
BEGIN
    SELECT n.VAITRO, n.MADV, d.TENDV
    INTO p_VAITRO, p_MADV, p_TENDV
    FROM user_admin.NHANVIEN n
    LEFT JOIN user_admin.DONVI d ON n.MADV = d.MADV
    WHERE n.MANV = p_MANV;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_VAITRO := NULL;
        p_MADV := NULL;
        p_TENDV := NULL;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Lỗi khi lấy thông tin giảng viên: ' || SQLERRM);
END;
/
-- LẤY DANH SÁCH MÔN HỌC, LỚP GIÁO VIÊN DẠY
CREATE OR REPLACE PROCEDURE GET_MAMM_BY_GV (
    p_MAGV IN VARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_CURSOR FOR
    SELECT DISTINCT M.MAMM, H.TENHP
    FROM MOMON M
    JOIN HOCPHAN H ON M.MAHP = H.MAHP
    WHERE M.MAGV = p_MAGV;
END;
/

-- LẤY DANH SÁCH SINH VIÊN THEO MAMM
CREATE OR REPLACE PROCEDURE GET_SV_BY_MAMM (
    p_MAMM IN VARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_CURSOR FOR
    SELECT S.MASV, S.HOTEN, S.PHAI, S.NGSINH, S.TINHTRANG
    FROM DANGKY D
    JOIN SINHVIEN S ON D.MASV = S.MASV
    WHERE D.MAMM = p_MAMM;
END;
/


-- LẤY ĐIỂM SINH VIÊN THEO MASV VÀ MAMM
CREATE OR REPLACE PROCEDURE GET_DIEM_BY_SV (
    p_MAMM IN VARCHAR2,
    p_MASV IN VARCHAR2,
    p_DIEMTH OUT NUMBER,
    p_DIEMQT OUT NUMBER,
    p_DIEMCK OUT NUMBER,
    p_DIEMTK OUT NUMBER
) AS
BEGIN
    SELECT DIEMTH, DIEMQT, DIEMCK, DIEMTK
    INTO p_DIEMTH, p_DIEMQT, p_DIEMCK, p_DIEMTK
    FROM DANGKY
    WHERE MAMM = p_MAMM AND MASV = p_MASV;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_DIEMTH := NULL;
        p_DIEMQT := NULL;
        p_DIEMCK := NULL;
        p_DIEMTK := NULL;
END;
/

-- LẤY DANH SÁCH ĐƠN VỊ
CREATE OR REPLACE PROCEDURE GET_KHOA_LIST (
    p_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_CURSOR FOR
    SELECT MADV, TENDV FROM DONVI;
END;
/

-- LẤY MÔN HỌC
CREATE OR REPLACE PROCEDURE GET_MONHOC_BY_KHOA (
    p_MADV IN VARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_CURSOR FOR
    SELECT DISTINCT H.MAHP, H.TENHP
    FROM HOCPHAN H
    JOIN MOMON M ON H.MAHP = M.MAHP
    JOIN NHANVIEN N ON M.MAGV = N.MANV
    WHERE N.MADV = p_MADV;
END;
/
SHOW USER;

CREATE OR REPLACE PROCEDURE user_admin.GET_SV_BY_MON_LOP (
    p_user_id    IN  VARCHAR2,
    p_maHP       IN  VARCHAR2,
    p_lop        IN  VARCHAR2,
    p_sv_cursor  OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_sv_cursor FOR
        SELECT sv.MASV,
               sv.HOTEN,
               sv.PHAI,
               sv.NGSINH,
               sv.DCHI,
               sv.DT,
               sv.KHOA,
               sv.TINHTRANG,
               dk.MAMM,
               mm.MAHP,
               mm.HK,
               mm.NAM
        FROM SINHVIEN sv
        JOIN DANGKY dk ON sv.MASV = dk.MASV
        JOIN MOMON mm ON dk.MAMM = mm.MAMM
        JOIN HOCPHAN hp ON mm.MAHP = hp.MAHP
        WHERE mm.MAGV = p_user_id
          AND mm.MAHP = p_maHP
          AND sv.KHOA = p_lop;
END;
/

GRANT EXECUTE ON USER_ADMIN.GET_GV_INFO TO PUBLIC;

GRANT EXECUTE ON USER_ADMIN.GET_GV_INFO TO PUBLIC;

GRANT EXECUTE ON USER_ADMIN.GET_DIEM_BY_SV TO PUBLIC;

GRANT EXECUTE ON USER_ADMIN.GET_SV_BY_MON_LOP TO PUBLIC;

GRANT EXECUTE ON USER_ADMIN.GET_SV_BY_MAMM TO PUBLIC;

GRANT EXECUTE ON USER_ADMIN.GET_MAMM_BY_GV TO PUBLIC;

