alter session set container=ATBM;
-- chạy = user_admin
DROP PROCEDURE GET_SINHVIEN_MASV_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_MASV_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT MASV FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_MASV_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_HOTEN_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_HOTEN_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT HOTEN FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_HOTEN_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_PHAI_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_PHAI_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT PHAI FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_PHAI_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_NGSINH_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_NGSINH_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT TO_CHAR(NGSINH, 'DD/MM/YYYY') FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_NGSINH_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_DCHI_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_DCHI_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT DCHI FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_DCHI_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_DT_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_DT_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT DT FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_DT_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_KHOA_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_KHOA_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT KHOA FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_KHOA_SV TO SV;

DROP PROCEDURE GET_SINHVIEN_TINHTRANG_SV;
CREATE OR REPLACE PROCEDURE GET_SINHVIEN_TINHTRANG_SV(p_result OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN p_result FOR
        SELECT TINHTRANG FROM user_admin.SINHVIEN;
END;
/
GRANT EXECUTE ON user_admin.GET_SINHVIEN_TINHTRANG_SV TO SV;


DROP PROCEDURE GET_DANGKY_SV;
CREATE OR REPLACE PROCEDURE GET_DANGKY_SV(p_result OUT SYS_REFCURSOR)
AUTHID CURRENT_USER
IS
BEGIN
    OPEN p_result FOR
        SELECT MASV, MAMM, DIEMTH, DIEMQT, DIEMCK, DIEMTK FROM user_admin.DANGKY;
END;
/
GRANT EXECUTE ON user_admin.GET_DANGKY_SV TO SV;

/*
DECLARE
    cur SYS_REFCURSOR;
    masv VARCHAR2(20);
    mamm VARCHAR2(20);
    diemth NUMBER;
    diemqt NUMBER;
    diemck NUMBER;
    diemtk NUMBER;
BEGIN
    -- Gọi procedure
    user_admin.GET_DANGKY_SV(cur);

    -- Đọc dữ liệu từ cursor
    LOOP
        FETCH cur INTO masv, mamm, diemth, diemqt, diemck, diemtk;
        EXIT WHEN cur%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Mã SV: ' || masv || ' | Môn: ' || mamm || ' | TK: ' || diemtk);
    END LOOP;

    CLOSE cur;
END;
*/
DROP PROCEDURE ADD_DANGKY_SV;
CREATE OR REPLACE PROCEDURE ADD_DANGKY_SV(
    p_mamm IN VARCHAR2
)
AUTHID CURRENT_USER
IS
BEGIN
    INSERT INTO user_admin.DANGKY (MASV, MAMM)
    VALUES ( SYS_CONTEXT('USERENV', 'SESSION_USER') , p_mamm );
    COMMIT;
END;
/
GRANT EXECUTE ON user_admin.ADD_DANGKY_SV TO SV;

/*
EXECUTE user_admin.ADD_DANGKY_SV('MM0100');
*/

DROP PROCEDURE DELETE_DANGKY_SV;
CREATE OR REPLACE PROCEDURE DELETE_DANGKY_SV(
    p_mamm IN VARCHAR2
)
AUTHID CURRENT_USER
IS
BEGIN
    DELETE FROM user_admin.DANGKY
    WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER') AND MAMM = p_mamm;
    COMMIT;
END;
/
GRANT EXECUTE ON user_admin.DELETE_DANGKY_SV TO SV;
/*
EXECUTE user_admin.DELETE_DANGKY_SV('MM0100');
*/

DROP PROCEDURE UPDATE_DANGKY_SV;
CREATE OR REPLACE PROCEDURE UPDATE_DANGKY_SV(
    p_mamm_1 IN VARCHAR2,
    p_mamm_2 IN VARCHAR2
)
AUTHID CURRENT_USER
IS
BEGIN
    UPDATE user_admin.DANGKY
    SET MAMM = p_mamm_2
    WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER') AND MAMM = p_mamm_1;
    COMMIT;
END;
/
GRANT EXECUTE ON user_admin.UPDATE_DANGKY_SV TO SV;


DROP PROCEDURE UPDATE_SINHVIEN_SV;
CREATE OR REPLACE PROCEDURE UPDATE_SINHVIEN_SV(
    p_dia_chi_2 IN VARCHAR2,
    p_dien_thoai_2 IN VARCHAR2
)
AUTHID CURRENT_USER
IS
BEGIN
    UPDATE user_admin.SINHVIEN
    SET DCHI = p_dia_chi_2, DT = p_dien_thoai_2
    WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER');
    COMMIT;
END;
/
GRANT EXECUTE ON user_admin.UPDATE_SINHVIEN_SV TO SV;
