--2
GRANT CONNECT, RESOURCE TO user_admin;

GRANT EXECUTE ON SA_LABEL_ADMIN TO user_admin;
GRANT EXECUTE ON SA_COMPONENTS TO user_admin;
GRANT EXECUTE ON SA_POLICY_ADMIN TO user_admin;
GRANT EXECUTE ON SA_USER_ADMIN TO user_admin;
GRANT EXECUTE ON CHAR_TO_LABEL TO user_admin;

--15
GRANT CONNECT TO u1;
GRANT CONNECT TO u2;
GRANT CONNECT TO u3;
GRANT CONNECT TO u4;
GRANT CONNECT TO u5;
GRANT CONNECT TO u6;
GRANT CONNECT TO u7;
GRANT CONNECT TO u8;
