--3
DROP TABLE THONGBAO;
CREATE TABLE THONGBAO (
    ID NUMBER PRIMARY KEY,
    NOIDUNG VARCHAR2(4000)
);
SELECT * FROM THONGBAO;
SELECT table_name FROM user_tables WHERE table_name = 'THONGBAO';
SELECT LABEL_COL FROM THONGBAO;
--14.
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (1, 'Thong bao cho tat ca truong don vi', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'TRUONGDV::'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (2, 'Thong bao cho tat ca nhan vien', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'NHANVIEN::'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (3, 'Thong bao cho tat ca sinh vien', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'SINHVIEN::'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (4, 'Thong bao cho sinh vien khoa Hoa o co so 1', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'SINHVIEN:HOA:CS1'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (5, 'Thong bao cho sinh vien khoa Hoa o co so 2', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'SINHVIEN:HOA:CS2'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (6, 'Thong bao cho sinh vien khoa Hoa o ca hai co so', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'SINHVIEN:HOA:CS1,CS2'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (7, 'Thong bao cho tat ca sinh vien o ca hai co so', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'SINHVIEN::CS1,CS2'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (8, 'Thong bao cho truong khoa Hoa o co so 1', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'TRUONGDV:HOA:CS1'));
INSERT INTO THONGBAO (ID, NOIDUNG, LABEL_COL) VALUES (9, 'Thong bao cho truong khoa Hoa o ca hai co so', CHAR_TO_LABEL('NOTIFICATION_POLICY', 'TRUONGDV:HOA:CS1,CS2'));

--17
GRANT SELECT ON THONGBAO TO u1;
GRANT SELECT ON THONGBAO TO u2;
GRANT SELECT ON THONGBAO TO u3;
GRANT SELECT ON THONGBAO TO u4;
GRANT SELECT ON THONGBAO TO u5;
GRANT SELECT ON THONGBAO TO u6;
GRANT SELECT ON THONGBAO TO u7;
GRANT SELECT ON THONGBAO TO u8;